/* ===========================================================
   Offertje auto-blog - topic queue + post file helpers.
   Shared by the CLI (scripts/generate-post.mjs) and the
   Vercel cron route (api/index.js).
   =========================================================== */

import { readdirSync, writeFileSync, existsSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const CONTENT_DIR = resolve(__dirname, '..', '..', 'content', 'blog');

/** Load the topic backlog (content/blog/_topics.mjs). */
export async function loadTopics() {
    const mod = await import(pathToFileURL(join(CONTENT_DIR, '_topics.mjs')).href);
    return Array.isArray(mod.default) ? mod.default : [];
}

/** Slugs of posts that already exist on local disk. */
export function existingSlugs(dir = CONTENT_DIR) {
    if (!existsSync(dir)) return new Set();
    return new Set(
        readdirSync(dir)
            .filter((f) => f.endsWith('.mjs') && !f.startsWith('_'))
            .map((f) => f.replace(/\.mjs$/, ''))
    );
}

/** First topic whose post does not exist yet (skip set = already-taken slugs). */
export async function nextTopic(skip = existingSlugs()) {
    const topics = await loadTopics();
    return topics.find((t) => t && t.slug && !skip.has(t.slug)) || null;
}

/**
 * Serialize a post object to a .mjs module. We use JSON so that
 * bodyHtml (which contains HTML and quotes) needs no escaping and
 * can never break the file - unlike a hand-written template literal.
 */
export function serializePost(obj) {
    return `// Auto-generated by Offertje blog engine. Safe to edit by hand.\nexport default ${JSON.stringify(obj, null, 2)};\n`;
}

/** Write the post to content/blog/<slug>.mjs and return the path. */
export function writePostFile(obj, dir = CONTENT_DIR) {
    const path = join(dir, `${obj.slug}.mjs`);
    writeFileSync(path, serializePost(obj));
    return path;
}
